### PR TITLE
Remove fluentd

### PR DESCRIPTION
**Pull request by yasn77**
fluent-bit 1.7.1 supports AWS outputs so there is no need for memory hungry
fluentd deployment

This commit also introduces tolerations for clusters that have node taints.

### CODE REVIEW

**Comment by yasn77** [comment]
This is quite a big change, but I think overall it is better. There is no reason to run fluentd if we don't want to. It's horrible for memory consumption.

**Review by QuentinBisson — CHANGES_REQUESTED** [review]
In general, this looks good to me, especially the removal of fluentd but could you explain your change in the changelog?

Also, could you split your PR in smaller ones in the future to make it easier to review as this amount of changes makes me trust you more than actually review the changes in the PR?

**Comment by webwurst** [comment]
When we remove `fluentd` completely, does anything speak against using something from upstream like https://github.com/fluent/helm-charts/tree/master/charts/fluent-bit?

**Comment by yasn77** [comment]
> In general, this looks good to me, especially the removal of fluentd but could you explain your change in the changelog?
>

Changelog updated 👍🏽 
 
> Also, could you split your PR in smaller ones in the future to make it easier to review as this amount of changes makes me trust you more than actually review the changes in the PR?

Multiple PRs would have been difficult since it's tricky to remove Fluentd in small parts. But what I should have done is broke it up into multiple commits, then you could review commits rather than one massive commit. Sorry about that, I'll try and be more considerate in the future :)

**Comment by yasn77** [comment]
> When we remove `fluentd` completely, does anything speak against using something from upstream like https://github.com/fluent/helm-charts/tree/master/charts/fluent-bit?

Yeh I think we should, but what I like about this app is that it's opinionated for our use cases. But no reason why we couldn't just take the upstream and modify with our bits.

For now, though, I just need to get this done.

**Review by pipo02mix — APPROVED** [review]
LGTM when Tobias and Quentin are happy

**Review by QuentinBisson — APPROVED** [review]

**Pull request merged**
